# Generated by Django 4.2.16 on 2025-01-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_image_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='recipe',
            name='allergen_free',
            field=models.ManyToManyField(blank=True, related_name='allergen_free_recipes', to='recipes.allergen'),
        ),
    ]
