services:
  - type: web
    name: recipesharing
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn recipesharing.wsgi"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: recipedb
          property: connectionString

databases:
  - name: recipedb
